alter table public.orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists city text not null default '',
  add column if not exists address_extra text not null default '',
  add column if not exists payment_method text not null default 'cash_on_delivery';

create unique index if not exists orders_order_number_key on public.orders(order_number);
