create table if not exists public.categories (
  id text primary key,
  label text not null,
  sort_order integer not null default 0
);

create table if not exists public.products (
  id text primary key default gen_random_uuid()::text,
  name text not null,
  category_id text not null references public.categories(id),
  secondary_category_id text references public.categories(id),
  price integer not null check (price >= 0),
  original_price integer check (original_price is null or original_price >= 0),
  beer_format text check (beer_format is null or beer_format in ('latas', 'botellas')),
  image_url text,
  volume text,
  stock text not null default 'available' check (stock in ('available', 'low', 'sold_out', 'hidden')),
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.delivery_zones (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price integer not null check (price >= 0),
  eta text not null,
  description text,
  polygon jsonb not null default '[]'::jsonb,
  match_terms text[] not null default '{}',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  address text not null,
  city text not null default '',
  address_extra text not null default '',
  manual_address boolean not null default false,
  zone_name text not null,
  subtotal integer not null,
  discount integer not null default 0 check (discount >= 0),
  coupon_code text,
  delivery integer not null,
  total integer not null,
  payment_method text not null default 'cash_on_delivery',
  payment_status text not null default 'pending',
  fulfillment_status text not null default 'new',
  price_adjustment_active boolean not null default false,
  price_adjustment_percent integer not null default 0 check (price_adjustment_percent >= 0 and price_adjustment_percent <= 300),
  notes text,
  created_at timestamptz not null default now()
);

create unique index if not exists orders_order_number_key on public.orders(order_number);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null,
  line_total integer not null
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.categories (id, label, sort_order)
values
  ('promociones', 'Promociones', 1),
  ('cervezas', 'Cervezas', 2),
  ('piscos', 'Piscos', 3),
  ('vinos', 'Vinos', 4),
  ('destilados', 'Destilados', 5),
  ('extras', 'Extras', 6)
on conflict (id) do update
set label = excluded.label,
    sort_order = excluded.sort_order;

insert into public.products (id, name, category_id, price, image_url, volume, stock, featured)
values
  ('promo-pisco-energetica', 'Promo Pisco + Energetica', 'promociones', 12990, 'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?auto=format&fit=crop&w=900&q=80', '1 botella + 2 latas', 'available', true),
  ('promo-six-pack', 'Six Pack Lager', 'promociones', 6990, 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=900&q=80', '6 x 355 cc', 'available', true),
  ('mistral-35', 'Mistral 35', 'piscos', 8990, 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=900&q=80', '750 cc', 'available', false),
  ('kunstmann-torobayo', 'Kunstmann Torobayo', 'cervezas', 1790, 'https://images.unsplash.com/photo-1618885472179-5e474019f2a9?auto=format&fit=crop&w=900&q=80', '330 cc', 'sold_out', false)
on conflict (id) do nothing;

insert into public.site_settings (key, value)
values (
  'main',
  '{
    "businessName": "Fonocopete Concepción",
    "maintenanceMode": false,
    "maintenanceMessage": "Fonocopete Penquista se encuentra temporalmente fuera de servicio. Estamos realizando mejoras para brindarte una mejor experiencia. Inténtalo nuevamente más tarde.",
    "whatsappNumber": "56989351855",
    "contactEmail": "fonocopetepenquista@gmail.com",
    "mercadoPagoLink": "https://www.mercadopago.cl/",
    "coupons": [],
    "productPriceAdjustment": {
      "enabled": false,
      "percentage": 0,
      "scheduleEnabled": false,
      "startDate": "",
      "endDate": "",
      "startTime": "00:00",
      "endTime": "23:59"
    },
    "newsletter": {
      "enabled": false,
      "provider": "mailchimp",
      "audienceId": "",
      "formUrl": "",
      "defaultTags": "promociones, clientes web"
    },
    "email": {
      "transactionalEnabled": false,
      "fromName": "Fonocopete Concepcion",
      "fromEmail": "fonocopetepenquista@gmail.com",
      "ownerEmail": "fonocopetepenquista@gmail.com",
      "replyToEmail": "fonocopetepenquista@gmail.com",
      "smtpHost": "",
      "smtpPort": "587",
      "smtpUser": "",
      "credentialsConfigured": false
    },
    "bankDetails": {
      "bank": "Banco de Chile",
      "accountHolder": "Fonocopete Penquista",
      "accountType": "Cuenta Corriente",
      "accountNumber": "12345678",
      "rut": "11.111.111-1",
      "email": "pagos@fonocopetepenquista.cl"
    }
  }'::jsonb
)
on conflict (key) do nothing;
